services:
  postgres:
    image: postgres:16
    container_name: pg_benchmark
    restart: unless-stopped
    environment:
      POSTGRES_DB: commerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  postgres_json:
    image: postgres:16
    container_name: pg_benchmark_json
    restart: unless-stopped
    environment:
      POSTGRES_DB: commerce_sql_json
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pg_data_json:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: mongo_benchmark
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: commerce
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  neo4j:
    image: neo4j:5
    container_name: neo4j_benchmark
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/MyStrongPassword25
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
    volumes:
    - neo4j_data:/data
    - ./graph/graph_csv:/var/lib/neo4j/import

volumes:
  pg_data:
  pg_data_json:
  mongo_data:
  neo4j_data:

